name: Check Lines of Localize Files

on:
  push:

jobs:
  check_json_lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install jsonlint -g

      - name: Check JSON Files
        run: |
          # Navigate to the languages directory
          cd src/localize/languages

          # Get the list of all JSON files
          files=$(ls *.json)

          # Check the number of lines in the first file
          expected_lines=$(wc -l < "$files")

          # Loop through all files and check the line count
          for file in $files; do
            current_lines=$(wc -l < "$file")

            if [ "$current_lines" -ne "$expected_lines" ]; then
              echo "ERROR: $file does not have the same number of lines as other JSON files."
              exit 1
            fi
          done
