name: HACS Validation

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  hacs:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: "actions/checkout@v6"
      - name: Validate HACS
        uses: "hacs/action@main"
        with:
          category: "plugin"
